project:
  type: website

website:
  title: "Körsbär"
  navbar:
    left:
      - href: index.qmd
        text: Hem
      - about.qmd
      - pollination.qmd
    pinned: true
  page-navigation: true
  
## comments:
##   hypothesis: true ## enable later

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



