project:
  type: website
  output-dir: _site

website:
  title: "Körsbär"

  navbar:
    left:
      - href: index.qmd
        text: Hem
      ## - about.qmd
      - choosing_variety.qmd
      - tables_comparison.qmd
      - sour_cherries.qmd
      - pollination_about.qmd
      - blooming.qmd
      - pollination_table.qmd
      - cultivation.qmd
      - recepies.rmd
      - terminology.qmd
      - resources.qmd
    pinned: true
    self-contained: true
    embed-resources: true
    subtitle: "Test subtitle"
    
  page-navigation: true ## No effect unless there are sections?

  ## sidebar: ## Sidebar necessary for sections (?)
  ##   contents:
  ##     - section: "Hur funkar pollination"
  ##       contents:
  ##         - href: pollination.qmd
  ##     - section: "Pollinationstabell"
  ##       contents:
  ##         - href: pollination_table.qmd

## comments:
##   hypothesis: true ## enable later

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



