project:
  type: website

website:
  title: "Körsbär"
  navbar:
    left:
      - href: index.qmd
        text: Hem
      - about.qmd
      - pollination.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



