
## Scientific papers

ORIGINAL RESEARCH article
Front. Plant Sci., 09 January 2020
Sec. Plant Breeding
Volume 10 - 2019 | https://doi.org/10.3389/fpls.2019.01647
Genetic Dissection of Bloom Time in Low Chilling Sweet Cherry (Prunus avium L.) Using a Multi-Family QTL Approach
"https://www.frontiersin.org/articles/10.3389/fpls.2019.01647/full

"Bloom time in sweet cherry (Prunus avium L.) is a highly heritable trait that varies between genotypes and depends on the environmental conditions. Bud-break occurs after chill and heat requirements of each genotype are fulfilled, and dormancy is released."

"Early blooming cultivars are susceptible to spring frost damage in cold regions (Luedeling, 2012), while late blooming cultivars can exhibit irregular floral development and low fruit set due to warm temperatures during the flowering period (Mahmood et al., 2000; Atkinson et al., 2013). The biological control of BT is complex and is known to depend on environmental signals during the winter and spring seasons (Abbott et al., 2015; Fadón and Rodrigo, 2018). Fruit trees like sweet cherry require a period of chilling temperatures followed by a period of warm temperatures to induce blooming (Lang et al., 1987). In Prunus species, several studies indicate that BT is more dependent on chilling than on heat requirement and that there is large variation in these requirements among individuals of the same species (Campoy et al., 2011; Okie and Blackburn, 2011; Sánchez-Pérez et al., 2012; Castède et al., 2014)."

"BT was evaluated for each progeny and the parental cultivars during 4 years (2015 to 2018). During the flowering season, blooming stage was evaluated 3 days per week (every 2–3 days) and BT was recorded when approximately 75% of the floral buds reached stage F (full bloom; Baggiolini, 1980). BT data were expressed as Julian Days (JD; days from January 1st). "

The datasets generated for this study can be found in the Genome database for Rosaceae, https://www.rosaceae.org/accession https://www.rosaceae.org/accession number tfGDR1040.






" Maximum pollen hydration and pollen germination occurred on the stigmas within 2 days of bloom, depending on cultivar and air temperature. Pollen hydration and germination, and ovule senescence accelerated under warmer temperatures. At 7 days post-anthesis and under 24 °C approximately 80% of ‘Rainier’ ovules were viable compared to 30% in the three other cultivars. Under moderate temperature (18 °C) which mimicked the field average flowering temperature, ovule of the two high productivity cherry cultivars, ‘Rainier’ and ‘Sweetheart’, kept full viabilities for 3–4 days post-anthesis while only 1 day for the two low productivity cultivars ‘Benton’ and ‘Tieton’. These results reveal that low commercial productivity of sweet cherry cultivars in the Pacific Northwest (PNW) of U.S. is likely due to rapid ovule senescence, a condition exacerbated in warm conditions https://www.sciencedirect.com/science/article/abs/pii/S030442381830431X"

Norway:
Modeling of sweet cherry flowering based on temperature and phenology in a mesic Nordic climate
Authors:   	M. Meland, O. Frøynes, L. Coop, C. Kaiser
Keywords:   	cherry (Prunus avium L), anthesis, chill units, flowering, dormancy, heat units
DOI:   	10.17660/ActaHortic.2017.1162.4

"Phenological observations are considered to be sensitive tools for identifying plant responses to climatic changes. Over the last 10 years, the onset of the phenophases of sweet cherry (Prunus avium L.) during spring tended to be earlier than the previous two decades in Ullensvang, western Norway. The effects of air temperature during the winter and spring months were evaluated during two quinquennia (5-year periods), 1996-2000 (Q1) and 2003-2007 (Q2) selected due to similar mean winter and early summer temperatures, but markedly different spring temperatures. Average January-February temperatures were similar (3.3°C) in both of these two 5-year periods. However, average March and April temperatures were slightly warmer (4.0 vs. 3.2°C) and (7.3 vs. 6.9°C), respectively, in Q2 vs. Q1. These increases resulted in significantly earlier flower development. Average temperatures during the first half of May were similar for both quinquennia (10.2 vs. 10.1°C). The start of flowering (first bloom) of early maturing 'Burlat' and mid-season 'Van' were significantly different. Timing of flowering phenophases were statistically different between Q1 and Q2 for both cultivars. Mean data for 'Burlat' and 'Van' first bloom were 8 days earlier during Q2, May 2 for 'Burlat' and May 1 for 'Van'. Full bloom occurred 3 days after first bloom and flowering ended 14 days after first bloom. First bloom during Q2 required 221 Baskerville-Emin Growing degree days (GDD) using a base temperature of 2°C. For the same time period in Q1, only 197 GDD were accumulated, which supports the observed temperature differences. Furthermore, we propose a flowering model for full bloom of both 'Burlat' and 'Van' in Ullensvang, which requires 254 Baskerville-Emin GDD using a base of 2°C starting on March 1."
