---
title: "Val av sort"
---

När du planterar körsbär bör du se till att ha mer än en sort. Den främsta anledningen till detta är att många sötkörsbär kan inte befruktas av sig själva eller andra individer av samma sort. Sorterna måste vara genetiskt kompatibla med varandra och blomma samtidigt. Se sidan om [pollination](pollination_about.qmd) för mer om det. Även de sorter som kan befrukta sig själva ger bättre skörd om de befruktas av andra. 

Det finns många sorter av körsbär. En sort benämns företrädesvis med artnamn och sortnamn, tex _Prunus avium_ 'Merton Glory'. Dock används i praktiken samma namn för sorter som är genetiskt olika och tvärtom kan sorter som är genetiskt lika benämnas olika. [Se](https://pub.epsilon.slu.se/8732/7/nybom_et_al_120419.pdf)

## Varför plantera flera sorter?

- Kan vara nödvändigt för att få frukt (se ovan).

- Vissa sorter är lämpliga för matlagning och andra bör ätas färska.

- Om de mognar under olika perioder har du tillgång till körsbär under en längre tid.

- Olika sorter kan trivas olika bra i just din trädgård, så det kan vara bra att prova olika.


## Några egenskaper av betydelse för val av sort

- Härdighet: Vilket klimat de kan odlas i. Anges ofta i zoner numrerade 1-8 där 1 är mildast och 8 kärvast. Kolla zonkartan för att se vilken zon du bor i. Lokalt klimat kan påverkas av närhet till stora vatten (klimatet blir ofta mildare), läge osv.

<!-- Digital zonkarta från Riksförbundet Svensk Trädgård , OBS! Avgift för publicering/länkning!!, https://zonkartan.se/, Via blomsterlandet: https://www.blomsterlandet.se/tips-rad/tradgard/tradgardsskotsel/zonkarta-vagledning-till-vaxtval/ -->

<!-- Kartan gäller endast för vedartade växter, som träd, buskar, rosor, fruktträd och klängväxter. För perennernas härdighet eller övervintringsförmåga används ett annat system där skyddat läge och väldränerad växtplats är viktiga faktorer.  -->

- Läge: Behov av sol/möjlighet att växa i skugga.

- Motståndskraft mot sjukdomar.

- Motståndskraft mot att spricka vid rikligt sommarregn.

- Smak: Grad av sötma, syra, arom, etc.

- Storlek och form (vissa sorter är hjärtformade) på bären.

- Trädets utseende och storlek (beror också på vilken _grundstam_ som används).

- Skördens riklighet.

- Färgen och glansen på skalet.

- Färgen på saften.

- Fruktköttets konsistens, saftighet och färg.

- Lämplighet för syltning, saftning, konservering, matlagning.

- Tillgänglighet i handeln.

- Kvalitetsmärkning. Vissa sorter finns som "E-plantor" (markeras med ett E efter namnet hos försäljaren). Se sidan om terminologi för mer om det. [Här](https://eplanta.com/kategorier_hemtradgarden/tradgardens-skafferi/) kan du se vilka sorter av körsbär mm där E-märkta exemplar finns att köpa.

<!-- Frost can be extremely damaging to blossom and will reduce your crop. It can be useful to choose trees in late flowering groups if you have a late last frost. -->

## Surkörsbär, skillnad mot sötkörsbär

- Mer syrliga än sötkörsbär.

<!-- Morello cherry trees fruit on younger wood than sweet varieties, and thus can be pruned harder. -->

- Alla sorter av surkörsbär är självfertila, dvs kräver inte pollen från en annan individ för att bära frukt.

- Kräver mer kväve och vatten. Bättre tolerans mot dålig dränering av jorden.

- Mer motståndskraftiga mot skadeinsekter och sjukdomar.

- Är tetraploider med 2n=32 kromosomer (Sötkörsbär är diploida<!-- och har 16 kromosomer som bildar 8 par.  -->). En tertaploid sort kan ha upp till fyra alleler/varianter i samma locus.

## Några intressanta sorter

Lapins

Sen sort som mognar i slutet av juli eller början av augusti.

Garden Focused: "Only really suitable for growing in warmer parts of the UK because blossom first appears on average in the second to third week of April (pollination group 2 to 3)."

OLLINATION PARTNERS FOR LAPINS CHERRY
Lapins is self-fertile and and does not need a suitable pollination partner to produce fruit. Lapins is in pollination group 2 to 3. The following varieties produces blossom at roughly the same time (mid to late April) and will be pollinated by Lapins. They are easily obtainable in the UK:

Penny, pollination group 3 to 4, eating variety
Summer Sun, pollination group 3 to 4, eating variety
Van, pollination group 3, eating variety

HOW LARGE WILL LAPINS GROW
On Colt rootstock Lapins will grow to about 4m / 13ft tall when it has reached maturity after about 7 years. With an annual prune it can easily be kept to 2.4m / 8ft high for a manageable tree in most gardens. On Gisela 5 rootstock it will grow to approximately 2.4m / 8ft.

<!-- RHS recommends: When choosing a variety, it’s worth looking out for any with an RHS Award of Garden Merit (AGM). These are recommended by RHS fruit experts, as they performed well in trials – see our list of AGM fruit and veg. -->


Van

"Excellent pollinator"

Stella

If you only want to grow one cherry tree, choose Stella - self-fertile, easy to grow, and a good pollinator.

Morello is a traditional late-season acid or sour-cherry. It's a good choice if you need a trained tree for a north-facing situation. Flowers over a long period. The blossom of Morello cherry is particularly long-lasting and compatible, making it an excellent pollinator of most other cherries (sweet or sour).

Gardenfocused:
https://www.gardenfocused.co.uk/fruitarticles/cherry/varieties.php
Se beskrivningar i "cherries_gardenfocused_uk_varieties_description.csv"
Alla utom dessa anges som self-sterile:
"MORELLO","Self-fertile",
"SKEENA","Self-fertile",
"STELLA","Self-fertile"
"SUMMER SUN","Self-fertile"
"SUNBURST","Self-fertile",
"SWEETHEART","Self-fertile",
"SYLVIA","Self-fertile",
"LAPINS"
Alla utom dessa anges som Use: Eating
"MORELLO", "Use: Cooking"


<!-- Market intermediaries indicated a willingness to pay producers more per pound for fruit greater than 2.5 cm in diameter, firmness above 300 g/mm, and SSC above 18 °Brix -->


# Grundstammar

Körbär ympas vanligen på en trädstam från en annan art (oftast genom _okulering_). Typen av grundstam påpverkar bland annat:

- Trädets storlek
- Härdighet
- När trädet börjar bära frukt
- Hur gammalt trädet kan bli

## Olika grundstammar för körsbär

**Colt**

- Medelstarkväxande
- Sluthöjd 3-4 m efter 8 år
- God bördighet
- Ger frukt inom 1-2 år
- Klarar något sämre jord
- Kräver stöd de första åren.
- Zon 1-3

<!-- Ger relativt stora träd, 70-80% av fröstam. -->

**Gisela**

- Ger mindre träd än colt.
- Sluthöjden varierar beroende på körsbärssort, 3-4 m
- Ger frukt efter 1-2 år
- God härdighet (ymplingen avmognar tidigt)
- Zon 1-4(5)

<!-- 35% av av Prunus avium, blir 3,5-4,5 m  -->

**Prunus avium**

- Starkväxande
- Högre träd (kan vara svårplockad pga höjd), 20-30 m
- Kronans diameter ca 10 m. Upprätt, något pyramidal form (beror på ymlingen sort?)
- God förankring i jorden
- Något senare fruktsättning
- Zon 1-5
- Används ej för sötkörsbär (som ju är av arten _Prunus avium_).

**Prunus cerasus**

- Ger mindre något mer svagväxande träd.
- Både söt- och surkörsbär (_Prunus cesarus_)?

**Prunum mahaleb**

- Används ej för sötkörsbär (?)
- Zon 1-3
- För torra, sandiga jordar


<!-- Prunus padus -->
<!-- Prunus spinosa -->

<!-- Prunus ’Colt’ = rätt stora träd, ca 70-80% storlek av Prunus avium, klarar zon I-III. -->

<!-- Prunus ’Gisela 5’ = blir mindre träd, ca 35% storlek av Prunus avium, ungefär 3,5-4,5 m höga, klarar zon I-V (VI) -->

<!-- Om du vill läsa mer om grundstammar för körsbär så rekommenderar jag varmt blogginlägget Grundstammar del 4 – körsbär och boken Skogsträdgården: odla ätbart överallt av Philipp Weiss & Annevi Sjöberg 2018:424-426 -->"

<!-- Skogsträdgårdsbloggen tabell:  -->
<!-- https://skogsträdgården.stjärnsund.nu/grundstammar-del-4-korsbar/ -->
