---
title: "Grundstammar"
---

<!-- # Grundstammar {#sec-grundstam} -->

Körbär ympas vanligen på en trädstam från en annan art (oftast genom _okulering_). Typen av grundstam påverkar bland annat:

- Trädets storlek
- Härdighet
- När trädet blommar
- När trädet börjar bära frukt
- Hur gammalt trädet kan bli

## Olika grundstammar för körsbär

Ett icke-ympat körsbärsträd bli kring 6 m högt beroende på sort.

För en grundstm kan anges till vilken % av standardträdets höjd (det som ympas på rotstocken) det blir.

<!-- It is important to remember though that a cherry tree on Colt rootstock, pruned once a year, can easily be restricted to 3m / 10ft high. -->

**Colt**

- En hybrid från _Prunus avium_ och _Prunus pseudocerasus_
- Medelstarkväxande.
- Sluthöjden 3.5-4.5 m efter 8 år (60-70% av standard). Kan hållas till 3 m med beskärning.
- God bördighet.
- Passar sämre för sorter med riklig produktion och leder då till små, defomerade bär. Man kan då avlägsa en del av blomknopparna för att minska problemet.
<!-- - Colt is resistant to phytophthora root rot, bacterial canker, and stem-pitting, although is susceptive to crown gall.  -->
- Colts vigör påverkas inte av virus, medan Gisela 5 har en något mindre vigör om det är virusdrabbat.
- Ger frukt inom 1-2 år.
- Klarar något sämre jord än Gisela 5.
- Kräver stöd de första åren.
- Grundstammen kan skadas vid hård vinter, men blommorna har mindre risk för frostskada.
- Zon 1-3.


<!-- Ger relativt stora träd, 70-80% av fröstam. -->

**Gisela 5**

- En hybrid mellan _Prunus cerasus_ (surkörsbär) and _Prunus canascens_.
- Ger mindre träd än colt.
- Höjden blir ca 3 m efter 5 år. Sluthöjden varierar beroende på körsbärssort, 2.5-3  m (40-50% av standard). Kan hållas till 2 m med beskärning.
- Behöver stödpåle hela livet.
- Ger frukt efter 1-2 år.
- God härdighet (ymplingen avmognar tidigt).
- Ger tidigare blomning med några dagar, vilket kan öka risken för frosstkadade knoppar/blommor.
- Tidigarelägger blomningen med några dagar och ökar därmed risken för froststkador.
- Klarar hård vinterkyla bätre än Colt.
- Lägre träd (ökar risken för frosstkada).
- Zon 1-4(5).

<!-- 35% av av Prunus avium, blir 3,5-4,5 m  -->

**Prunus avium**

- Starkväxande
- Högre träd (kan vara svårplockad pga höjd), 20-30 m
- Kronans diameter ca 10 m. Upprätt, något pyramidal form (beror på ymplingen sort?)
- God förankring i jorden
- Något senare fruktsättning
- Zon 1-5
- Används ej för sötkörsbär (som ju är av arten _Prunus avium_).

**Prunus cerasus**

- Ger mindre något mer svagväxande träd.
- Både söt- och surkörsbär (_Prunus cerasus_)?

**Prunum mahaleb**

- Används ej för sötkörsbär (?)
- Zon 1-3
- För torra, sandiga jordar

<!-- Prunus padus -->
<!-- Prunus spinosa -->

<!-- Prunus ’Colt’ = rätt stora träd, ca 70-80% storlek av Prunus avium, klarar zon I-III. -->

<!-- Prunus ’Gisela 5’ = blir mindre träd, ca 35% storlek av Prunus avium, ungefär 3,5-4,5 m höga, klarar zon I-V (VI) -->

<!-- Om du vill läsa mer om grundstammar för körsbär så rekommenderar jag varmt blogginlägget Grundstammar del 4 – körsbär och boken Skogsträdgården: odla ätbart överallt av Philipp Weiss & Annevi Sjöberg 2018:424-426 -->

<!-- Skogsträdgårdsbloggen tabell:  -->
<!-- https://skogsträdgården.stjärnsund.nu/grundstammar-del-4-korsbar/ -->

