---
title: "Surkörsbär"
---

Surkörsbär (_Prunus cerasus_) har troligen uppkommit genom en korsning av sötkörsbär (_Prunus Avium_) och dvärgkörsbär (_P Fructiosa_). De delas ibland in i _moreller/brunbär_ (mörkröd färg och färgad saft) respektive _amareller/klarbär_ (ljusare färg och ofärgad saft). De är ofta _självfertila_ och blommar i allmänhet senare än sötkörsbär.

## Surkörsbär, skillnad mot sötkörsbär

- Mer syrliga än sötkörsbär.

<!-- Morello cherry trees fruit on younger wood than sweet varieties, and thus can be pruned harder. -->

- De flesta sorter av surkörsbär är självfertila (tex 'Skuggmorell'), dvs kräver inte pollen från en annan individ för att bära frukt. Vissa är delvis- (tex 'Kelleriis 16') eller helt (tex 'Tschernokorka') själv-inkompatibla.

- Kräver mer kväve och vatten. Bättre tolerans mot dålig dränering av jorden.

- Mer motståndskraftiga mot skadeinsekter och sjukdomar.

- Är allotetraploider med 2n = 4x = 32 kromosomer dvs har två uppsättningar diploida koromosomer från olika arter. _Prunus Ceracus_ antas vara en hybrid som skapats genom "ickereducerade" (diploida) celler från _Prunus Avium_ och normala celler från _P Fructiosa_. En tetraploid sort kan ha upp till fyra alleler/varianter i samma locus. Sötkörsbär är diploida, 2n=2x=16<!-- och har 16 kromosomer som bildar 8 par.  -->.

- Blommar vanligen senare än sötkörsbär och är därför inte så lämpliga som pollinerare av dessa.

- Kan i allmänhet användas för syltning, saftning och matlagning.

## Några surkörsbär

**Fanal**: Morell. Självfertil. Mycket sur och kraftig smak. Tysk.

<!-- Tysk sort som växer medelstarkt. Morelltyp. Självfertil. Medelstort bär. Mycket sur och kraftig smak. Mycket rikbärande. Angrips av bakterios. Bra till kommersiell odling. Zon 4 -->

**Kelleris 16 (syn. Morellenfeuer)**: Morell. Delvis självfertil. Mild, syrlig smak.

<!-- Dansk sort .  Morelltyp. Trädet växer ganska starkt  och upprätt med spetsiga grenvinklar. Blommar efter lövsprickningen. Självfertil. Ganska litet bär med mild, syrlig smak. Angrips lätt av sjukdomar. -->

**Kirsa**: Amarell. Buske.

<!-- Buskkörsbär. 1,5 m. Amarelltyp. zon 5 -->

**Lettisk Låg**: Morell. Självfertil. Söta bär. Buske.

<!-- Buskkörsbär av morelltyp. Busken blir bara 2,5 m hög. Självfertil. Bären är söta. Kan klara sig ända upp i Zon7. -->

**Montmorency (syn. Königliche Amarelle)**: Amarell. Starkväxande. Fransk.

<!-- Fransk sort. Trädet växer mycket starkt. Amarelltyp. Medelstor frukt. Frisk. Medelgod bördighet. Inte särskilt härdig. -->

**Nordia**: Morell. Självfertil. Buske. Svensk.

<!-- Svenskt buskkörsbär av morelltyp. självfertil. zon 5 -->

**Ostheimer**: Morell. Självsteril. Buskformigt träd. Blommar tidigt. Tysk.

<!-- Tysk 1700tals sort. Litet, buskformig träd. Självsteril. Blommar tidigt. Morelltyp. Knopparna känsliga för stark kyla i mars. Mycket bördig om det finns rätt pollinerare. Frisk men mottaglig för Monilia. -->

**Pernilla**: Morell. Självfertil. Buske. Svensk.

<!-- Svenskt buskkörsbär av morelltyp. 2m. Självfertil. zon 5. -->

**Sikkola**: Amarell. Självfertil. Små bär.

<!-- Amarelltyp. Små bär. Självfertil. Klarat -40C. -->

**Skuggmorell**: Morell. Självfertil. Syrlig. Tysk.

<!-- Tysk sort från 1500talet. Syrliga bär. Själfertil. Zon 5. -->

**Tshernokorka**: Morell. Anges i vissa källor vara självfertil men enligt genetiska analyser är den inte det. Mycket sur. Starkväxande. Rysk.

<!-- Rysk sort av morelltyp. Starkväxande med hängande skott. Medelstort, violett rött bär. Mycket sur. Mognar tidigt. Frisk och bördig sort. Lämplig som industriråvara. -->

<!-- Beutelsbacher Rexell -->

<!-- Chokladnaja -->

<!-- Ryskt buskkörsbär av morelltyp. 2m. Mörkbruna bär. Självfertil. Zon 6. -->


<!-- Huvimaja -->

<!-- Amarelltyp. Självfertil. Zon 6. -->
<!-- Inkeroisten Kirsikka -->

<!-- Amarelltyp. Stor buske. Zon 5 -->

<!-- Karneol -->


<!-- Körös, Körösi Meggy,  Körösska Visen -->

<!-- Ungersk sort. Trädet växer starkt och upprätt. Blomningen är mycket senare än lövsprickningen. Amarelltyp. Självsteril. Smaken är sur och ganska mild. Frisk sort. Bra till färskkonsumtion. -->

<!-- Ludwigs Fruhe -->

<!-- Minister von Podbielski -->

<!-- Tysk sort från 1902. Trädet är mycket starkvuxet. Självsteril. Morelltyp. Stor, välsmakande frukt. Låg bördighet. Inte särskilt härdig. -->

<!-- Rauhala -->

<!-- Amarelltyp. Litet träd. Söta bär. Självfertil. Zon 6. -->

<!-- Rubin,  Heimanns Rubin -->

<!-- Tysk sort. Trädet växer svagt. Sen blomning. Självfertil. Morelltyp. Små, mycket syrliga bär. Angrips av bakterios och grå monilia. -->

<!-- Safir -->
<!-- Schwäbische Steinweichsel -->

<!-- Ungarishe Traubige -->

 
<!-- Källor -->

<!-- Ingevald Fernqvist (redaktör): Körsbär, En pomologi över i Sverige prövade körsbärssorter. -->

<!-- https://handbok.alternativ.nu/Odling/Frukt_och_b%C3%A4r/Surk%C3%B6rsb%C3%A4r.html -->
