---
title: "Sorter"
execute:
  echo: false
---

När du planterar körsbär bör du se till att ha mer än en sort. Den främsta anledningen till detta är att många sötkörsbär kan inte befruktas av sig själva eller andra individer av samma sort. Sorterna måste vara genetiskt kompatibla med varandra och blomma samtidigt. Se sidan om [pollination](pollination_about.qmd) och [pollinationsschemat](pollination_table.qmd) för mer om det. Även de sorter som kan befrukta sig själva ger bättre skörd om de befruktas av andra. 

## Varför plantera flera sorter?

- Kan vara nödvändigt för att få frukt (se ovan).

- Vissa sorter är lämpliga för matlagning och andra bör ätas färska.

- Om de mognar under olika perioder har du tillgång till körsbär under en längre tid.

- Olika sorter kan trivas olika bra i just din trädgård, så det kan vara bra att prova olika.

## Några egenskaper att ta hänsyn till

- Härdighet: Vilket klimat de kan odlas i. Anges ofta i zoner numrerade 1-8 där 1 är mildast och 8 kärvast. Kolla [zonkartan](https://www.plantagen.se/vaxtzoner.html) för att se vilken zon du bor i. Lokalt klimat kan påverkas av närhet till stora vatten (klimatet blir ofta mildare), läge osv.

<!-- Digital zonkarta från Riksförbundet Svensk Trädgård , OBS! Avgift för publicering/länkning!!, https://zonkartan.se/, Via blomsterlandet: https://www.blomsterlandet.se/tips-rad/tradgard/tradgardsskotsel/zonkarta-vagledning-till-vaxtval/ -->

<!-- Kartan gäller endast för vedartade växter, som träd, buskar, rosor, fruktträd och klängväxter. För perennernas härdighet eller övervintringsförmåga används ett annat system där skyddat läge och väldränerad växtplats är viktiga faktorer.  -->

- Läge: Behov av sol/möjlighet att växa i skugga.

- Motståndskraft mot sjukdomar.

- Blomningstid: Eftersom blommorna förstörs av frost bör blomningstiden anpassas till när sista frosten brukar vara där du bor.

- Motståndskraft mot att spricka vid rikligt sommarregn.

- Smak: Grad av sötma, syra, arom, etc.

- Storlek och form (vissa sorter är hjärtformade) på bären.

- Trädets utseende och storlek. Beror också på vilken _grundstam_ (se @sec-grundstam) som används.

- Skördens riklighet och tidpunkt (olika **mognadstid** ger längre skördesäsong).

- Färgen och glansen på skalet.

- Färgen på saften.

- Fruktköttets konsistens, saftighet och färg.

- Lämplighet för syltning, saftning, konservering, matlagning. I allmänhet är _surkörsbär_ lämpade för syltning och konservering.

- Grundstam: Vilken grundstam sorten är ympad på.

- Tillgänglighet i handeln.

- Sötkörsbär kan ha svårt att klara de svenska förhållandena om de har annan härkomst och exempelvis har _odlats upp_ vid varmare breddgrader.

- Kvalitetsmärkning. Vissa sorter finns som "E-plantor" (markeras med ett E efter namnet hos försäljaren). Se [Ordboken](terminology.qmd) för mer om det. [Här](https://eplanta.com/kategorier_hemtradgarden/tradgardens-skafferi/) kan du se vilka sorter av körsbär mm där E-märkta exemplar finns att köpa.

<!-- Frost can be extremely damaging to blossom and will reduce your crop. It can be useful to choose trees in late flowering groups if you have a late last frost. -->

- Att välja åtminstone en självfertil sort gör att du är garanterad att få viss skörd.

# Surkörsbär

Surkörsbär (_Prunus cerasus_) har troligen uppkommit genom en korsning av sötkörsbär (_Prunus Avium_) och dvärgkörsbär (_P Fructiosa_). De delas ibland in i _moreller/brunbär_ (mörkröd färg och färgad saft) respektive _amareller/klarbär_ (ljusare färg och ofärgad saft). De är ofta _självfertila_ och blommar i allmänhet senare än sötkörsbär. Surkörsbären är syrligare än sötkörsbären och passar vanligen bättre för syltning och matlagning.

## Surkörsbär, skillnad mot sötkörsbär

- Mer syrliga än sötkörsbär.

<!-- Morello cherry trees fruit on younger wood than sweet varieties, and thus can be pruned harder. -->

- De flesta sorter av surkörsbär är självfertila (tex 'Skuggmorell'), dvs kräver inte pollen från en annan individ för att bära frukt. Vissa är delvis- (tex 'Kelleriis 16') eller helt (tex 'Tschernokorka') själv-inkompatibla.

- Kräver mer kväve och vatten. Bättre tolerans mot dålig dränering av jorden.

- Mer motståndskraftiga mot skadeinsekter och sjukdomar.

- Blommar vanligen senare än sötkörsbär och är därför inte så lämpliga som pollinerare av dessa.

- Kan i allmänhet användas för syltning, saftning och matlagning.

- Är allotetraploider med 2n = 4x = 32 kromosomer dvs har två uppsättningar diploida koromosomer från olika arter. _Prunus ceracus_ antas vara en hybrid som skapats genom "ickereducerade" (diploida) celler från _Prunus avium_ och normala celler från _P fructiosa_. En tetraploid sort kan ha upp till fyra alleler/varianter i samma locus. Sötkörsbär är diploida, 2n=2x=16<!-- och har 16 kromosomer som bildar 8 par.  -->.


## Några surkörsbär

**Fanal**: Morell. Självfertil. Mycket sur och kraftig smak. Tysk.

<!-- Tysk sort som växer medelstarkt. Morelltyp. Självfertil. Medelstort bär. Mycket sur och kraftig smak. Mycket rikbärande. Angrips av bakterios. Bra till kommersiell odling. Zon 4 -->

**Kelleris 16 (syn. Morellenfeuer)**: Morell. Delvis självfertil. Mild, syrlig smak.

<!-- Dansk sort .  Morelltyp. Trädet växer ganska starkt  och upprätt med spetsiga grenvinklar. Blommar efter lövsprickningen. Självfertil. Ganska litet bär med mild, syrlig smak. Angrips lätt av sjukdomar. -->

**Kirsa**: Amarell. Buske.

<!-- Buskkörsbär. 1,5 m. Amarelltyp. zon 5 -->

**Lettisk Låg**: Morell. Självfertil. Söta bär. Buske.

<!-- Buskkörsbär av morelltyp. Busken blir bara 2,5 m hög. Självfertil. Bären är söta. Kan klara sig ända upp i Zon7. -->

**Montmorency (syn. Königliche Amarelle)**: Amarell. Starkväxande. Fransk.

<!-- Fransk sort. Trädet växer mycket starkt. Amarelltyp. Medelstor frukt. Frisk. Medelgod bördighet. Inte särskilt härdig. -->

**Nordia**: Morell. Självfertil. Buske. Svensk.

<!-- Svenskt buskkörsbär av morelltyp. självfertil. zon 5 -->

**Ostheimer**: Morell. Självsteril. Buskformigt träd. Blommar tidigt. Tysk.

<!-- Tysk 1700tals sort. Litet, buskformig träd. Självsteril. Blommar tidigt. Morelltyp. Knopparna känsliga för stark kyla i mars. Mycket bördig om det finns rätt pollinerare. Frisk men mottaglig för Monilia. -->

**Pernilla**: Morell. Självfertil. Buske. Svensk.

<!-- Svenskt buskkörsbär av morelltyp. 2m. Självfertil. zon 5. -->

**Sikkola**: Amarell. Självfertil. Små bär.

<!-- Amarelltyp. Små bär. Självfertil. Klarat -40C. -->

**Skuggmorell**: Morell. Självfertil. Syrlig. Tysk.

<!-- Tysk sort från 1500talet. Syrliga bär. Själfertil. Zon 5. -->

**Tshernokorka**: Morell. Anges i vissa källor vara självfertil men enligt genetiska analyser är den inte det. Mycket sur. Starkväxande. Rysk.

<!-- Rysk sort av morelltyp. Starkväxande med hängande skott. Medelstort, violett rött bär. Mycket sur. Mognar tidigt. Frisk och bördig sort. Lämplig som industriråvara. -->

<!-- Beutelsbacher Rexell -->

<!-- Chokladnaja -->

<!-- Ryskt buskkörsbär av morelltyp. 2m. Mörkbruna bär. Självfertil. Zon 6. -->


<!-- Huvimaja -->

<!-- Amarelltyp. Självfertil. Zon 6. -->
<!-- Inkeroisten Kirsikka -->

<!-- Amarelltyp. Stor buske. Zon 5 -->

<!-- Karneol -->


<!-- Körös, Körösi Meggy,  Körösska Visen -->

<!-- Ungersk sort. Trädet växer starkt och upprätt. Blomningen är mycket senare än lövsprickningen. Amarelltyp. Självsteril. Smaken är sur och ganska mild. Frisk sort. Bra till färskkonsumtion. -->

<!-- Ludwigs Fruhe -->

<!-- Minister von Podbielski -->

<!-- Tysk sort från 1902. Trädet är mycket starkvuxet. Självsteril. Morelltyp. Stor, välsmakande frukt. Låg bördighet. Inte särskilt härdig. -->

<!-- Rauhala -->

<!-- Amarelltyp. Litet träd. Söta bär. Självfertil. Zon 6. -->

<!-- Rubin,  Heimanns Rubin -->

<!-- Tysk sort. Trädet växer svagt. Sen blomning. Självfertil. Morelltyp. Små, mycket syrliga bär. Angrips av bakterios och grå monilia. -->

<!-- Safir -->
<!-- Schwäbische Steinweichsel -->

<!-- Ungarishe Traubige -->

 
<!-- Källor -->

<!-- Ingevald Fernqvist (redaktör): Körsbär, En pomologi över i Sverige prövade körsbärssorter. -->

<!-- https://handbok.alternativ.nu/Odling/Frukt_och_b%C3%A4r/Surk%C3%B6rsb%C3%A4r.html -->


# Grundstammar {#sec-grundstam}

Körbär ympas vanligen på en trädstam från en annan art (oftast genom _okulering_). Typen av grundstam påverkar bland annat:

- Trädets storlek
- Härdighet
- När trädet blommar
- När trädet börjar bära frukt
- Hur gammalt trädet kan bli

## Olika grundstammar för körsbär

Ett icke-ympat körsbärsträd blir kring 6 m högt beroende på sort.

För en grundstam kan anges till vilken % av standardträdets höjd (det som ympas på rotstocken) det blir.

<!-- It is important to remember though that a cherry tree on Colt rootstock, pruned once a year, can easily be restricted to 3m / 10ft high. -->

**Colt**

- En hybrid från _Prunus avium_ och _Prunus pseudocerasus_
- Medelstarkväxande.
- Sluthöjden 3.5-4.5 m efter 8 år (60-70% av standard). Kan hållas till 3 m med beskärning.
- God bördighet.
- Passar sämre för sorter med riklig produktion och leder då till små, defomerade bär. Man kan då avlägsa en del av blomknopparna för att minska problemet.
<!-- - Colt is resistant to phytophthora root rot, bacterial canker, and stem-pitting, although is susceptive to crown gall.  -->
- Colts vigör påverkas inte av virus, medan Gisela 5 har en något mindre vigör om det är virusdrabbat.
- Ger frukt inom 1-2 år.
- Klarar något sämre jord än Gisela 5.
- Kräver stöd de första åren.
- Grundstammen kan skadas vid hård vinter, men blommorna har mindre risk för frostskada.
- Zon 1-3.


<!-- Ger relativt stora träd, 70-80% av fröstam. -->

**Gisela 5**

- En hybrid mellan _Prunus cerasus_ (surkörsbär) and _Prunus canascens_.
- Ger mindre träd än colt.
- Höjden blir ca 3 m efter 5 år. Sluthöjden varierar beroende på körsbärssort, 2.5-3  m (40-50% av standard). Kan hållas till 2 m med beskärning.
- Behöver stödpåle hela livet.
- Ger frukt efter 1-2 år.
- God härdighet (ymplingen avmognar tidigt).
- Ger tidigare blomning med några dagar, vilket kan öka risken för frosstkadade knoppar/blommor.
- Tidigarelägger blomningen med några dagar och ökar därmed risken för froststkador.
- Klarar hård vinterkyla bätre än Colt.
- Lägre träd (ökar risken för frosstkada).
- Zon 1-4(5).

<!-- 35% av av Prunus avium, blir 3,5-4,5 m  -->

**Prunus avium**

- Starkväxande
- Högre träd (kan vara svårplockad pga höjd), 20-30 m
- Kronans diameter ca 10 m. Upprätt, något pyramidal form (beror på ymplingen sort?)
- God förankring i jorden
- Något senare fruktsättning
- Zon 1-5
- Används ej för sötkörsbär (som ju är av arten _Prunus avium_).

**Prunus cerasus**

- Ger mindre något mer svagväxande träd.
- Både söt- och surkörsbär (_Prunus cerasus_)?

**Prunum mahaleb**

- Används ej för sötkörsbär (?)
- Zon 1-3
- För torra, sandiga jordar

<!-- Prunus padus -->
<!-- Prunus spinosa -->

<!-- Prunus ’Colt’ = rätt stora träd, ca 70-80% storlek av Prunus avium, klarar zon I-III. -->

<!-- Prunus ’Gisela 5’ = blir mindre träd, ca 35% storlek av Prunus avium, ungefär 3,5-4,5 m höga, klarar zon I-V (VI) -->

<!-- Om du vill läsa mer om grundstammar för körsbär så rekommenderar jag varmt blogginlägget Grundstammar del 4 – körsbär och boken Skogsträdgården: odla ätbart överallt av Philipp Weiss & Annevi Sjöberg 2018:424-426 -->

<!-- Skogsträdgårdsbloggen tabell:  -->
<!-- https://skogsträdgården.stjärnsund.nu/grundstammar-del-4-korsbar/ -->

# Beskrivning av sorter

## Några intressanta sorter

<!-- "Similarly, we find it necessary to suggest exceptional potential of combining mid-late flowering cultivars whose flowering period overlaps with that of the majority of other cultivars. Some earlier investigations point to high in vitro pollen germination in some of these cultivars − ‘Van’, ‘Compact Stella’ (CEROVIĆ et al., 2003), and in self-compatible ‘Sunburst’ and ‘Lapins’ (RADIČEVIĆ et al., 2008).  On the other hand, cultivars classified as those with extreme flowering period cannot be recommended as suitable pollenisers among these groups. ‘insufficient overlap in some seasons’ can be suitable in some seasons and localities, though the risk of insufficient overlap in full flowering remains. This can particularly be emphasized when relatively low temperatures occurring over the period of flowering onset in sweet cherry markedly postpone flowering onset in late flowering cultivars." -->


### Skuggmorell

_Prunus cerasus subsp. acida_ 

Synonymer: 'Schattenmorelle', 'Gr. Lange Lotkirsche', 'Nordkirsche', 'Schwarze Kirsche von Montreux', 'Späte Morelle'

Enligt vissa källor är blomningen långvarig och att Skuggmorell därför är en lämplig pollinatör även för sötkörsbär.

<!-- Morello is a traditional late-season acid or sour-cherry. It's a good choice if you need a trained tree for a north-facing situation. Flowers over a long period. The blossom of Morello cherry is particularly long-lasting and compatible, making it an excellent pollinator of most other cherries (sweet or sour). -->


<!-- Schattenmorellen: -->
<!--     'Beutelspacher Rexelle', eine relativ früh reifende Sorte -->
<!--     'Heimanns Rubin', eine Sorte mit großen Früchten (Synonym: 'Fanal') -->
<!--     'Kelleriis 14', eine Weiterzüchung der Sorte 'Schattenmorelle' -->
<!--     'Konserven-Weichsel', eine für warme Lage geeignete Sorte -->
<!--     'Morellenfeuer', eine beliebte Gartensorte (Synonym: 'Kelleriis 16') -->
<!--     'Ostheimer Weichsel', eine anspruchslose Sorte mit kleinen, aromatischen Früchten (Synonym: 'Preßsauerkirsche') -->
<!--     'Scharo', eine sehr triebfreudige Sorte -->
<!--     'Schattenmorelle', die wichtigste Sorte[1] (Synonyme: 'Gr. Lange Lotkirsche', 'Nordkirsche', 'Schwarze Kirsche von Montreux', 'Späte Morelle') -->

### Lapins

Blomningstiden anges olika i olika källor. Troligen är det en tidigblommande sort vars blommor riskerar skadas av frost. Självfertil. Uppges i England blomma samtidigt som 'Van', 'Summer Sun' och 'Penny'.

<!-- Garden Focused: "Only really suitable for growing in warmer parts of the UK because blossom first appears on average in the second to third week of April (pollination group 2 to 3)." -->

<!-- POLLINATION PARTNERS FOR LAPINS CHERRY -->
<!-- Lapins is self-fertile and and does not need a suitable pollination partner to produce fruit. Lapins is in pollination group 2 to 3. The following varieties produces blossom at roughly the same time (mid to late April) and will be pollinated by Lapins. They are easily obtainable in the UK: -->

<!-- Penny, pollination group 3 to 4, eating variety -->
<!-- Summer Sun, pollination group 3 to 4, eating variety -->
<!-- Van, pollination group 3, eating variety -->

<!-- HOW LARGE WILL LAPINS GROW -->
<!-- On Colt rootstock Lapins will grow to about 4m / 13ft tall when it has reached maturity after about 7 years. With an annual prune it can easily be kept to 2.4m / 8ft high for a manageable tree in most gardens. On Gisela 5 rootstock it will grow to approximately 2.4m / 8ft. -->

<!-- RHS recommends: When choosing a variety, it’s worth looking out for any with an RHS Award of Garden Merit (AGM). These are recommended by RHS fruit experts, as they performed well in trials – see our list of AGM fruit and veg. -->

### Van

Bra pollinatör.

<!-- "Excellent pollinator" -->

### Stella

Kan vara ett lämpligt val om man bara vill plantera ett körsbärsträd. Sorten är självfertil, lätta att odla och en bra pollinatör.


<!-- Gardenfocused: -->
<!-- https://www.gardenfocused.co.uk/fruitarticles/cherry/varieties.php -->
<!-- Se beskrivningar i "cherries_gardenfocused_uk_varieties_description.csv" -->

<!-- Alla utom dessa anges som self-sterile: -->
<!-- "MORELLO","Self-fertile", -->
<!-- "SKEENA","Self-fertile", -->
<!-- "STELLA","Self-fertile" -->
<!-- "SUMMER SUN","Self-fertile" -->
<!-- "SUNBURST","Self-fertile", -->
<!-- "SWEETHEART","Self-fertile", -->
<!-- "SYLVIA","Self-fertile", -->
<!-- "LAPINS" -->
<!-- Alla utom dessa anges som Use: Eating -->
<!-- "MORELLO", "Use: Cooking" -->


<!-- Market intermediaries indicated a willingness to pay producers more per pound for fruit greater than 2.5 cm in diameter, firmness above 300 g/mm, and SSC above 18 °Brix -->


### Andra sorter

**Allmän gulröd bigarrå**: God smak. Söt och syrlig. Kan användas för syltning.

**Sam**: God smak. Mörkröd.

Sam i kombination med Sunburst (Självfertil, samma blomningstid, fullt kompatibel; mognar samtidigt) eller Stella (självfertil, blommar ett steg tidigare, fullt kompatibel; mognar tidigare), eller Linda (samma blomningstid, fullt kompatibel; ej självfertil).

**Fryksås** eller Gårdebo? Zon 4

Van: God. Zon 4.

Regina



<!-- ## notes on naming -->

<!-- Note 'Stor svart bigarrå' not same as Knopfels schwarze? -->
<!-- Wexthuset skiljer dessa -->
<!-- Blomsterlandet säljer Prunus avium STOR SVART BIGARRÅ ('Grosse Schwarze Knorpelkirsche') https://www.wexthuset.com/fakta-och-rad/skotselrad-om-vaxter-i-kruka-och-tradgard/beskrivningar-odling-skotsel-bar-och-frukter/korsbar-odling-sorter -->
<!-- ## Note: Süßkirsche Büttner`s Rote Knorpelkirsche Alte Sorte mit Tradition, auch "Altenburger Melonenkirsche" genannt. -->


<!-- ## Note: -->
<!-- ## kauffs_kirsche  # samma som 'Knauff's Schwarze'? (den enda som hittas av google när man söker på Knauff)? ändrade till var knauffs_schwarze i den tidigare egna listan -->


