---
title: "Resurser"
---

Resurser och källor.

## Allmänt

[Prunus cerasus](https://en.wikipedia.org/wiki/Prunus_cerasus)

[Surkörsbär](https://en.wikipedia.org/wiki/Prunus_cerasus#Origins_and_cultivation)

<!-- Bok Webster A.D & Looney N.E (red) (1996) Cherries: Crop physiology, production and uses. Cambridge, CAB INTERNATIONAL Kap. 3, 5, 7, 8, 15. -->

<!-- https://svensktradgard.se/ -->

## Terminologi

[Taxonomi](https://botanicalsociety.org.za/the-science-of-names-an-introduction-to-plant-taxonomy/)

[Taxonomi](https://glossary.lias.net/wiki/Taxonomic_rank)

[Taxonomic rank in botany](https://en.wikipedia.org/wiki/Taxonomic_rank#Ranks_in_botany)

[Botanisk taxonomi](https://en.wikipedia.org/wiki/Taxonomic_rank#Ranks_in_botany)

## Om pollination

[Wikipedia om pollinering](https://sv.wikipedia.org/wiki/Pollinering)

[Plant fertilization video](https://study.com/academy/lesson/plant-fertilization-process-definition-quiz.html)

[Structure of reproductive organs and the sequence of events involved in plant sexual reproduction, image and description](https://www.researchgate.net/figure/Structure-of-reproductive-organs-and-the-sequence-of-events-involved-in-plant-sexual_fig1_303994517)

[Dubbelbefruktning](https://en.wikipedia.org/wiki/Double_fertilization)

[Difference Between Allogamy and Xenogamy](https://pediaa.com/difference-between-allogamy-and-xenogamy/)

[Vittrup 1998, om blomning och korpollination](https://www.actahort.org/books/423/423_4.htm)

## Pollinationstabeller

[ANFIC SWEET CHERRY COMPATIBILITY AND BLOOM TIMING](https://anfic.com.au/wp-content/uploads/2022/05/ANFIC-Sweet-Cherry-Pollination-Table-13042022.pdf): Australiensisk sida som visar genetisk kompatibilitet och blomningstid.

[Primrose UK pollinationsgrupper](https://www.primrose.co.uk/blog/plants/cherry-fruit-trees-pollination-varieties-guide/)
<!-- Self-sterile cherry trees require another variety flowering at the same time to ensure fertilisation. They are henceforth put into flowering groups from 1 (very early) to 6 (very late). A cherry tree can be partnered with a cherry that is plus or minus 1 (+-1) its own group. -->

[Sweet Cherry pollination table](https://anfic.com.au/wp-content/uploads/2020/07/ANFIC-Sweet-Cherry-Pollination-Table-06072020.pdf)

[UK pollniantion groups list common cherries](https://www.gardenfocused.co.uk/fruitarticles/cherry/pollination.php)

<!-- "Suitable pollination partners include those in the same pollination group and the pollination group above and below. For instance, Merton Bigarreau is in pollination 3. It can be pollinated by  varieties not only in pollination group three but also in the groups 2 and 4." -->

[Ashridge](https://www.ashridgetrees.co.uk/advice/pollinating-cherry-trees)

[Tree-connect](https://treeconnect.com/cherry-tree-pollenizer/)

[Bloom timing](https://treeconnect.com/cherry-tree-pollenizer/)

[Cummins nursery](https://www.cumminsnursery.com/learn-trees/fruit-tree-bloom-dates/)
<!-- "Because sweet cherry pollination is complicated, we always recommend that growers start with one self-fertile “universal pollenizer.” This way you are guaranteed to have at least some cherries in your crop. Once you start adding trees to your cherry collection, you will likely have questions about bloom times. The two lists below are groups that will not make good pairings because their bloom times are at the opposite ends of the sweet cherry bloom period:" -->
<!-- "We do not recommend using tart cherries as pollenizers for sweet cherries, as the bloom time for tart cherries is usually later than that of sweet cherries." -->

[Orange Pippin fruit tree pollination checker](https://www.orangepippintrees.co.uk/pollinationchecker.aspx)

<!-- https://www.hollandrosetta.com/en/planting-material/cherries/cherries/ -->

[Thomas pollination checker](https://thomasfruittrees.eu/pollinationchecker.aspx)

<!-- "Because of this uncertainty our pollination checker will only recommend varieties which flower at the same time and are universal pollinators. Universal pollinator varieties will pollinate all other cherry varieties which are in flower at the same time (with a few exceptions, for example Stella - a universal pollinator - will not pollinate Bing)." -->

[Tysk sida](https://www.baumpruefung.de/pflanzen-und-pflegen/kirsche-befruchtertabelle/): Anger även blomningstid

## Genetisk kompatibilitet

[Self-incompatibility (S) genotypes of cultivated sweet cherries – An overview update 2020](https://www.openagrar.de/receive/openagrar_mods_00064311). Denna artikel har länkade data med genotypning av S-allelerna för ett stort antal sorter.

[IDENTIFICATION OF SELF INCOMPATIBILITY GENOTYPES IN SWEET CHERRY COMMERCIAL CULTIVARS](http://www.agricultforest.ac.me/paper.php?id=3137)

[Incompatible (S-) genotypes of sweet cherry cultivars](https://www.sciencedirect.com/science/article/abs/pii/S0304423812004396)
<!-- An update of the S-genotype of 734 sweet cherries was summarized. The data includes results of 51 new varieties supplemented with data from various published sources and personal information up to 2012 -->

[Artikel om koppling mellan haplotyp och blomningstid](http://www.agricultforest.ac.me/paper.php?id=3137)

[Incompatible (S-) genotypes of sweet cherry cultivars (Prunus avium L.)](https://www.sciencedirect.com/science/article/abs/pii/S0304423812004396)

[RosBreed om inkompatibilitet](https://www.rosbreed.org/breeding/dna-tests/cherry/cross-compatibility)

<!-- https://link.springer.com/article/10.1007/s001220051700 -->


<!-- Schuster, Mirko Mirko (2020): Self-incompatibility (S) genotypes of cultivated sweet cherries – An overview update 2020. OpenAgrar Repository. Online unter: https://www.openagrar.de/receive/openagrar_mods_00064311. -->
<!-- - Här finns excelfiler för nedladdning -->

[Self‐incompatibility (S) locus region of the mutated S6‐haplotype of sour cherry (Prunus cerasus) contains a functional pollen S allele and a non‐functional pistil S allele, Yamane 2003](https://academic.oup.com/jxb/article/54/392/2431/621944). Ger visst stöd för att sötkörsbär kan pollinera surkörsbär.

## Sorter

[Trädgårdstrollets sortguide om sötkörsbär](https://www.tradgardstrollet.se/2023/06/08/sortguide-sotkorsbar/)

[Blekinge plantskola](https://organicfruittrees.eu/products/buttners-rote)
<!-- Mognad: juli = tidigt //aug = mellan // sept = sen -->
<!-- Skörd: bra / medel / liten -->

[Tyska wiki](https://de.wikipedia.org/wiki/Liste_von_Kirschsorten)

[Cherry tree comparison UK](https://www.gardenfocused.co.uk/fruitarticles/cherry/varieties.php)

[Eriksbo plantskola:](http://www.eriksbo-plantskola.se/): Bra information om många sorter, bland annat blomningstid.

[Specialty Produce](https://specialtyproduce.com/produce/Schattenmorelle_Cherries_17828.php): Beskriver bla smaken på et antal körsbär.

[Cherries of New York](http://www.chathamapples.com/CherriesNY/TCNYIndex.htm#INDEX)

<!-- Tysk sida: https://www.gartenbaumschule-becker.de/artikel/76864/suesskirsche-schneiders-spaete-knorpelkirsche -->

[Dave Wilson Nursery](https://www.wheretobuy.davewilson.com/product-information/product/cherries) <!-- Note: Has BT -->

[Van cherry](https://en.wikipedia.org/wiki/Van_cherry)

[Nybom 2012, Konsten att särskilja olika sorter av körsbär](https://pub.epsilon.slu.se/8732/7/nybom_et_al_120419.pdf): Beskriver hur olika sorter är besläktade och att många plantor inte är "sortäkta".

## Databaser och liknande

[RoSBREED](https://www.rosbreed.org/): Amerikansk databas från ett forskningsprojekt.

[Wenden 2016, A collection of European sweet cherry phenology data for assessing climate change](https://www.nature.com/articles/sdata2016108) : Data finns att ladda ner [här](https://datadryad.org/stash/dataset/doi:10.5061/dryad.1d28m).

[Self-incompatibility (S) genotypes of cultivated sweet cherries – An overview update 2020](https://www.openagrar.de/receive/openagrar_mods_00064311). Denna artikel har länkade data med genotypning av S-allelerna för ett stort antal sorter.

<!-- [EURISCO, europeisk databas](https://eurisco.ipk-gatersleben.de/apex/eurisco_ws/r/eurisco/eurisco-download-by-species) -->
<!-- Data descriptors: https://www.ecpgr.cgiar.org/fileadmin/templates/ecpgr.org/upload/NW_and_WG_UPLOADS/Prunus/EPDB_New_list_of_descriptors_2011.pdf -->

<!-- ## Bilder -->

<!-- [Körsbärsblomma, surkörsbär:](https://commons.wikimedia.org/wiki/File:Prunus_cerasus_blossom_1.jpg) -->

<!-- Note: Finns i hög upplösning. -->

[Genbanken](https://www.slu.se/centrumbildningar-och-projekt/nationellagenbanken/): Sticklingar kan beställas (?)

[Genbanken mandatsorter plommon och körsbär](https://www.slu.se/centrumbildningar-och-projekt/nationellagenbanken/vaxterna/frukten-i-nationellagenbanken/mandatsortlista-plommon/)

[Sorter i svenska genbanker](https://stud.epsilon.slu.se/182/1/vandermaarel_l_090515.pdf)

[iBulider](https://ibuilder-en.techinfus.com/chereshnya/sorta/): Lista ovanliga sorter

[Fruit characteristics](https://www.saplant.co.za/fruit-types/cherries/)

## Plantskolor

[Bloqvists](https://www.blomqvistplantskola.com/index.php?route=product/product&path=123&product_id=2372): Ovanligt utbud. Finland?

[Cramers](https://shop.cramersblommor.com/vaxter/tradgardsvaxter/frukttrad/korsbarstrad/): Stort utbud

[Blomsterlandet](https://www.blomsterlandet.se/produkter/vaxter/utomhus/frukttrad/korsbarstrad/sotkorsbar-donnissen-donissens-gelbe-knorpelkirsche-77981/): Stort utbud

[Svartbäckens](https://shop.svartbackens.com/korsbar): Har vissa något ovanligare sorter
