---
title: "Ordbok"
---


## Taxonomi

Genus (släkte): _Prunus_ (plommon, körsbär, aprikoser mfl)

Subgenus (undersläkte): _Prunus subg. Cerasus_ (körsbär)

Species (art): _Prunus cerasus_ (surkörsbär) och _Prunus avium_ (sötkörsbär)

Subspecies (underart): Tex _Prunus avium subsp. avium_

Varietas (variant): Tex _Prunus avium var. juliana_ (Hjärtkörsbär), _Prunus avium var. avium_ (Vanlig sötkörsbär), _Prunus avium var. duracina_ (Bigarrå).

"Sort": Tex _Prunus avium_ 'Merton Glory'. Kallas ibland "kultivar" när den framkorsats medvetet.

Släktnamnet skrivs med stor bokstav och artnamnet med liten.

Korsningar mellan två arter markeras med ett "x" mellan släktnamnet och artnamnet.

[Exempel](https://species.wikimedia.org/wiki/Prunus_avium_subsp._avium)

<!-- Om en växt är en korsning mellan två arter, markeras detta med ett x mellan släkt- och artnamnet, ex. Geranium x magnificum (=G. ibericum x G. platypetalum).  -->


**Förkortningar:**

subg. = subgenus

sp. = species

subs. = ssp. = subspecies

var. = v. = varietas 

form = f. = ? 

syn. = synonymt med

<!-- Genus: Prunus -->
<!-- Subgenus: P. subg. Cerasus -->
<!-- Species: Prunus avium -->
<!-- Subspecies: Prunus avium subsp. avium -->

<!-- Arten kan delas in i ett antal varieteter.  -->
<!--     Vanlig sötkörsbär (Prunus avium var. avium) – har små frukter, upp till 1 cm stora. Färgen på frukterna varierar från gult till rött eller svart. De har ofta en bitter smak.[källa behövs] -->
<!--     Bigarrå (Prunus avium var. duracina) – har stora frukter med fast fruktkött. De mognar ofta sent på säsongen. Det finns många sorter som hör till denna varietet. Även så kallade halvbigarråer är klassificerade som denna varietet. -->
<!--     Hjärtkörsbär (Prunus avium var. juliana) – har stora frukter med löst fruktkött. Sorter som 'Guigne d'Annonay', 'Elton', 'Frogmore Early', 'Knauff's Riesenkirsche', 'Merton Glory' och 'Valeska' räknas till hjärtkörsbäret. -->


<!-- Prunus avium L. syn. Cerasus avium Moench. -->

<!-- Påpekas skall att sp. används för en obestämd art. Om man t.ex. skriver Geranium sp. så menar man en art av släktet Geranium men man vill eller kan inte bestämma växten till art utan endast till släkte.  -->

<!-- Odlade växter har ofta registrerade namnsorter, dessa skrives med stor bokstav inom enkla apostrofer, ex. Geranium pratense 'Kashmir White'. Man kan också i vardagsbruk skriva enbart Geranium 'Kashmir White'.  -->

<!-- Om en växt är en korsning mellan två arter, markeras detta med ett x mellan släkt- och artnamnet, ex. Geranium x magnificum (=G. ibericum x G. platypetalum).  -->

<!-- Alternativa namn markeras med synonym, syn. (ex. Geranium lambertii syn. G. candicans).  -->

<!-- https://www.odla.nu/inspiration/lite-grundlaggande-botanik -->

## Benämningar av olika typer av körsbär

_Bigarrå_: Benämndes tidigare taxonomiskt _Prunus avium var. duracina_, kom senare att avse sorter med viss typ av fruktkött (fast), men numera menas oftast bara sötkörsbär. 

_Hjärtkörsbär_, Benämndes tidigare taxonomiskt _Prunus avium var. avium_. Avser numera vanligen endast att bären är hjärtformade. 

_Morell_: Surkörsbär med mörkröd färg och färgad saft (_Prunus cerasus var. austera_). Även "brunbär".

_Amarell_: Surkörsbär med ljusare färg och ofärgad saft (_Prunus cerasus var. cerasus_). Även "klarbär".

### I Tyskland

_Wilde Vogelkirsche_: Även "Waldkirsche" (_Prunus avium var. avium_), dvs vilda sötkörsbär. Små blad, svarta, saftiga, små frukter (< 1 cm), med sötsyrlig smak.

_Knorpelkirsche_: I Tyskland benämns vissa körsbär "Knorpelkirsche" (_Prunus avium var. duracina_). Dessa har vanligan mycket stora blad, stora (> 1 cm) svartröda frukter med gult eller rött fruktkött som är "broskigt" ("knorpelig") och fast. Även lokalt benämnda som "Krachkirsche", "Knubber" eller "Knupper".

_Herzkirsche_: Även "Weichkirsche" (_Prunus avium var. juliana_). Har större blad än de vilda sötkörsbären. Oftast stora (> 1 cm) svartröda, gula, eller vita frukter med mjukt, saftigt, och rött eller mörkrött fruktkött.


## Pollination och befruktning

Terminoligin är rörig och olika definitioner förekommer (tex anses ibland självpollination uteslutande betyda att pollen kommer från samma blomma).

_Självpollination (autogami)_: Pollen kommer från vilken blomma som helst på samma individ. Innebär att det blir mindre genetisk variation vid befruktningen.

<!-- Synonymer: Autogami, självbefruktning, eng. self-pollination, self-fertilization, "selfer". -->

_Korspollination (allogami)_: Pollen överförs mellan två olika individer. 

<!-- Synonymer: Allogami, korsbefruktning , eng. cross-pollination, cross-fertilization, "outcrosser", "outbreeder". -->

**I praktiken** brukar man i vardagligt tal används begreppen litet annorlunda:

"Korspollination": En viss sort (_Prunus avium_ 'Merton Glory') måste pollineras av en annan sort (tex _Prunus avium_ 'Allmän gulröd bigarrå') för att bära frukt. Dessa sorter kallas ibland "självsterila".

"Självfertila sorter": En sort som kan pollineras av samma sort (tex _Prunus avium_ 'Gårdebo').

<!--  korspollination, detsamma som allogami. se https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/korspollination -->

<!-- Pollinationsförloppen kan delas in på olika sätt, bl.a. i självpollination och korspollination. Självpollination (autogami), som förekommer t.ex. hos många korsblommiga växter, innebär att växten pollinerar sig själv, https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/pollination -->

<!-- https://en.wikipedia.org/wiki/Allogamy -->

<!-- _Xenogami_ : En undergrupp till allogami.  -->

<!-- korsbefruktning: korsbefruktning, befruktningsförlopp då könsceller från två genetiskt olika individer smälter samman (se https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/korsbefruktning)-->

<!-- A flower is self-pollinated (a “selfer”) if pollen is transferred to it from any flower of the same plant and cross-pollinated (an “outcrosser” or “outbreeder”) if the pollen comes from a flower on a different plant. (se https://www.britannica.com/science/self-pollination) -->

<!-- Allogamy vs Xenogamy There are two types of pollinations known as self pollination and cross pollination. Allogamy and xenogamy are the two types of cross pollinations that occur during the sexual reproduction of higher plants. Flower is the sexual organ of angiosperms. Stamen is the male part of the flower, which contains anther and filamentous. Pistil is the female part of the flower, which contains stigma, style, and ovary. Unisexual flowers contain pistil and the stamens in separate flowers, enhancing cross pollination. Bisexual flowers contain both pistil and stamens in the same flower, enhancing self pollination. The main difference between allogamy and xenogamy is that allogamy is the deposition of pollen grains from the anther of the one flower on the stigma of another flower, either in the same plant or a in a different plant of the same species whereas xenogamy is the deposition of pollen grains from the anther of one flower on the stigma of a genetically different flower of the same species. -->

<!-- Även om en växt är självfertil, eller självpollinerande, blir bäret eller frukten större och av högre kvalitet med korspollination. -->

<!-- Autogamy, or self-fertilization, refers to the fusion of two gametes that come from one individual. Autogamy is predominantly observed in the form of self-pollination -->

<!-- Korsbefruktning innebär att man korsar olika plantor för att få fram en växt med de egenskaper man önskar.  -->

<!-- Allogamy or cross-fertilization is the fertilization of an ovum from one individual with the spermatozoa of another. -->

<!-- In plants, allogamy is used specifically to mean the use of pollen from one plant to fertilize the flower of another plant and usually synonymous with the term "cross-fertilization" or "cross-pollination" (outcrossing).[4] The latter term can be used more specifically to mean pollen exchange between different plant strains or even different plant species (where the term cross-hybridization can be used) rather than simply between different individuals.[6] -->



<!-- [Blekinge plantskola](https://organicfruittrees.eu/products/lapins-korsbar?variant=40116019462281) -->

## Kvalitetsmärkning "E-planta"

Plantor med denna kvalitetsmärkning märks i handeln med "E" efter det vetenskapliga namnet.

E-planta är en ekonomisk förening som bildats av ett antal plantskolor.  E-plantsystemet omfattar produktutveckling, testning och marknadsföring av växter som är utvalda för svenskt klimat. Stiftelsen Trädgårdsodlingens Elitplantstation (EPS) äger varumärket E-planta och en expertgrupp där väljer ut de växter som E-märks. Gruppen har bred kompetens med representanter för forskning, plantskolor samt växtanvändare i både offentlig verksamhet och inom fritidsodlingen.

"E-planta" är en kvalitetsbeteckning på träd och buskar som hjälper växtanvändaren att välja ett säkert växtmaterial för svenskt klimat. Beteckningen finns även på fruktträd och bärbuskar som är testat fria från skadliga virus. <!-- E-et står för Elitplanta. -->

Växterna måste uppfylla höga krav på odlingsvärde, sort- och artäkthet samt sundhet innan de får kallas E-planta. Detta får man fram genom flera års provodling på olika platser i Sverige. Det ger pålitlig information om hur härdig en växt är och vilka prydnadsvärden den har. Flera av de E-märkta växterna har tagits fram genom olika projekt vid SLU, Sveriges lantbruksuniversitet.

**Fördelar med E-plantor:**

- Utvalda för svenskt klimat. Producerade i Sverige och därmed anpassade till svenskt klimat och takt med vår växtsäsong. Det minskar risken för vinterskador eftersom växterna inte slår ut för tidigt om våren och de invintrar i tid om hösten. Ger pålitliga zonangivelser.

- Provodlade på flera platser i landet vilket ger säkrare zonangivelser och korrekta växtbeskrivningar.

- Svenskproducerade. Kort väg från producent till konsument gör att växterna är i takt med vårt klimat.

- Art- resp. sortäkta Alla. E-plantor är art- respektive sortäkta vilket ger korrekta växtbeskrivningar och ett enhetligt växtmaterial. Ett dokumenterat och genetiskt väl definierat växtmaterial ger växter med sort- eller arttypiskt utseende.

- Friskt utgångsmaterial ger bättre motståndskraft mot sjukdomar/skadegörare. Detta leder till mindre bekämpningsbehov.

## Blommande växters utvecklingsstadier

Blommande växter kan beskrivas i sex olika fenologiska stadier. Dessa representeras av blomning, lövsprickning, fruktmognad, fröspridning, höstfärg och lövfällning. Se [SLU fenologobservationer](https://www.slu.se/centrumbildningar-och-projekt/svenska-fenologinatverket/manualer/). <!-- SLU  (2021)  -->

En annan indelning som används är den sk "Biologische Bundesanstalt,
Bundessortenamt and CHemical industry" (BBCH)-skalan:

    0: Germination, sprouting, bud development
    1: Leaf development
    2: Formation of side shoots, tillering
    3: Stem elongation or rosette growth, shoot development
    4: Development of harvestable vegetative plant parts, bolting
    5: Inflorescence emergence, heading
    6: Flowering
    7: Development of fruit
    8: Ripening or maturity of fruit and seed
    9: Senescence, beginning of dormancy

<!-- The "BBCH-scale (stone)" identifies the phenological development stages of stone fruit (cherry = Prunus cerasus, plum = Prunus domestica ssp. domestica, peach = Prunus persica, apricot = Prunus armeniaca). -->

<!-- See datafile "bbch_scale_stone_fruit.csv" -->

<!-- Phenological growth stages and BBCH-identification keys of stone fruit. The BBCH-scale (stone) identifies the phenological development stages of stone fruit (cherry = Prunus cerasus, plum = Prunus domestica ssp. domestica, peach = Prunus persica, apricot = Prunus armeniaca). It is a plant species specific version of the BBCH-scale. 2 -->

Varianten BBCH-scale (stone) beskriver stenfrukter, där ingår bla dessa faser:

**Principal growth stage 5: Inflorescence emergence**

51 	Inflorescence buds swelling: buds closed, light brown scales visible

53 	Bud burst: scales separated, light green bud sections visible

54 	Inflorescence enclosed by light green scales, if such scales are formed (not all cultivars)

55 	Single flower buds visible (still closed) borne on short stalks, green scales slightly open

56 	Flower pedicel elongating; sepals closed; single flowers separating

57 	Sepals open: petal tips visible; single flowers with white or pink petals (still closed)

59 	Most flowers with petals forming a hollow ball


**Principal growth stage 6: Flowering**

60 	First flowers open

61 	Beginning of flowering: about 10% of flowers open

62 	About 20% of flowers open

63 	About 30% of flowers open

64 	About 40% of flowers open

65 	Full flowering: at least 50% of flowers open, first petals falling

67 	Flowers fading: majority of petals fallen

69 	End of flowering: all petals fallen


**Principal growth stage 7: Development of fruit**

71 	Ovary growing; fruit fall after flowering

72 	Green ovary surrounded by dying sepal crown, sepals beginning to fall

73 	Second fruit fall

75 	Fruit about half final size

76 	Fruit about 60% of final size

77 	Fruit about 70% of final size

78 	Fruit about 80% of final size

79 	Fruit about 90% of final size


**Principal growth stage 8: Maturity of fruit and seed**

81 	Beginning of fruit colouring

85 	Colouring advanced

87 	Fruit ripe for picking

89 	Fruit ripe for consumption: fruit have typical taste and firmness 


## Gödsel

_Organisk gödsel_: Sådant som finns i naturen, såsom gödsel, kompost och gröna grödor (tex gräsklipp). 

_Oorganiskt gödsel_: Kemiska kombinationer blandade i vandel beroende på avsedd användning. Proportionerna av kväve, fosfor och kalium, de ämnen som behövs av nästan alla växter, anges som N-P-K-formuleringar, tex 10-10-10 eller 12-12-12. Andra makro- eller mikronäringsämnen kan också tillsättas som gödselmedel.

_Makronäringsämnen_: Tex svavel, magnesium och kalcium. 

_Mikronäringsämnen:_ Tex mangan, järn, zink, koppar, selen, mfl. 


